//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public int BookingGuestNum { get; set; }
        public System.DateTime BookingDate { get; set; }
        public string BookingTime { get; set; }
        public int LocationId { get; set; }
        public string UserId { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
