//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizza_Topping
    {
        public int Id { get; set; }
        public int PizzaPizzaId { get; set; }
        public int ToppingToppingId { get; set; }
    
        public virtual Pizza Pizza { get; set; }
        public virtual Topping Topping { get; set; }
    }
}
